theme: minima
title: caketussy®
author: made by leo
email: caketussy@gmail.com

description: a simple showcase of our products

social_links:
  instagram: https://instagram.com/caketussy
  github: https://github.com/caketussy

header_pages:
- about.md
- collabs.md
- products.md

footer_icons:
- username: caketussy
  url: https://instagram.com/caketussy
  icon: icon-instagram.svg
- username: caketussy
  url: https://youtube.com/@Caketussy
  icon: icon-youtube.svg

  paginate: 5
